backend:
  name: git-gateway
  branch: main   # or master if your repo uses that

media_folder: "uploads"      # files stored in repo
public_folder: "/uploads"    # how site references them

collections:
  - name: "content"
    label: "Site Content"
    files:
      - file: "content.md"
        label: "Main Content"
        name: "main"
        fields:
          - { label: "Hero", name: "hero", widget: "markdown" }
          - { label: "About", name: "about", widget: "markdown" }
          - { label: "Services", name: "services", widget: "markdown" }
          - { label: "Pricing", name: "pricing", widget: "markdown" }
          - { label: "Gallery", name: "gallery", widget: "markdown" }
          - { label: "Testimonials", name: "testimonials", widget: "markdown" }
          - { label: "Booking", name: "booking", widget: "markdown" }
          - { label: "Contact", name: "contact", widget: "markdown" }
          - { label: "FAQ", name: "faq", widget: "markdown" }
